#!/bin/bash

# TP3: Multiplicación de Matrices con MPI y MPI+OpenMP
# Este script muestra cómo usar y probar el proyecto

echo "=========================================="
echo "TP3: Multiplicación de Matrices"
echo "MPI Puro vs MPI+OpenMP Hybrid"
echo "=========================================="
echo ""

echo "ARCHIVOS DISPONIBLES:"
echo "  - matrices-mpi.c          : Implementación MPI puro"
echo "  - matrices-hybrid.c       : Implementación MPI+OpenMP"
echo "  - matrices-open-mp.c      : Referencia secuencial (OpenMP)"
echo "  - validate_small.c        : Validador para n=4"
echo ""

echo "EJECUTABLES COMPILADOS:"
echo "  - ./matrices-mpi          : Versión MPI puro"
echo "  - ./matrices-hybrid       : Versión Hybrid (MPI+OpenMP)"
echo "  - ./matrices-open-mp      : Referencia secuencial"
echo "  - ./validate_small        : Validador"
echo ""

echo "=========================================="
echo "EJEMPLOS DE USO:"
echo "=========================================="
echo ""

echo "1. MPI Puro (n=256, 2 procesos):"
echo "   $ mpirun -np 2 ./matrices-mpi 256"
echo ""

echo "2. MPI+OpenMP Hybrid (n=256, 2 procesos, 2 threads):"
echo "   $ export OMP_NUM_THREADS=2"
echo "   $ mpirun -np 2 ./matrices-hybrid 256"
echo ""

echo "3. Validación pequeña (n=4):"
echo "   $ ./validate_small"
echo ""

echo "4. Benchmark rápido:"
echo "   $ ./quick_benchmark.sh"
echo ""

echo "5. Benchmark completo:"
echo "   $ ./full_benchmark.sh"
echo ""

echo "=========================================="
echo "SCRIPTS DE BENCHMARK:"
echo "=========================================="
echo ""
echo "  - quick_benchmark.sh      : Benchmark rápido (n=256, np=2)"
echo "  - full_benchmark.sh       : Benchmark completo (n=128,256,512)"
echo "  - benchmark.sh            : Benchmark parametrizable"
echo "  - test_final.sh           : Test de validación final"
echo "  - test_validation.sh      : Comparar MPI vs secuencial"
echo ""

echo "=========================================="
echo "FORMATO DE SALIDA:"
echo "=========================================="
echo ""
echo "RESULT;n;tiempo;gflops;overhead%;constante"
echo ""
echo "Ejemplo:"
echo "RESULT;256;0.025938;1.293659;39.19%;511.992188"
echo ""

echo "=========================================="
echo "PARÁMETROS:"
echo "=========================================="
echo ""
echo "n           : Tamaño de matriz (debe ser múltiplo de 64 y numProcs)"
echo "np          : Número de procesos MPI (mpirun -np)"
echo "OMP_THREADS : Número de threads OpenMP (solo para matrices-hybrid)"
echo ""

echo "=========================================="
echo "VALIDACIÓN:"
echo "=========================================="
echo ""
echo "- MPI puro se valida contra referencia secuencial para n ≤ 128"
echo "- Tolerancia numérica: 1e-10"
echo "- Salida 'VALIDATION;OK' indica coincidencia"
echo ""

echo "=========================================="
echo "REFERENCIAS RÁPIDAS:"
echo "=========================================="
echo ""
echo "MPI Puro - Overhead bajo, escalable:"
echo "  $ mpirun -np 4 ./matrices-mpi 512"
echo ""
echo "Hybrid - 30-50% speedup localmente:"
echo "  $ export OMP_NUM_THREADS=2 && mpirun -np 4 ./matrices-hybrid 512"
echo ""
echo "Secuencial para comparación:"
echo "  $ ./matrices-open-mp 512"
echo ""
